# Python Programming

## Arrays

In mathematics, vectors can be expressed as either a row or column of elements and matrices are a rectangular array of elements. An individual element in a vector is identified by an index denoted using a subscript, e.g., $a_i$. The index is the position of the element in the vector starting at 1 for the first element. An individual element in a matrix is identified by two indices denoted in a subscript, e.g., $[A]_{ij}$, the first number corresponding to the row number and the second number corresponding to the column number.

$$
  \mathbf{a}  = \begin{pmatrix} a_1, & a_2, & \cdots & a_n \end{pmatrix}, \qquad
  \mathbf{b}  = \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{pmatrix}, \qquad
  A           = \begin{pmatrix}
            a_{11} & a_{12} & \cdots & a_{1n} \\
            a_{21} & a_{22} & \cdots & a_{2n} \\
            \vdots & \vdots & \ddots & \vdots \\
            a_{m1} & a_{m2} & \cdots & a_{mn}
          \end{pmatrix}.
$$

In computer programming, a vector or matrix is represented using an **array**. Arrays can be one-dimensional where they contain a single row or column of elements, similar to a vector, or two-dimensional array similar to a matrix. It is possible to have higher dimensional arrays but this is not recommended as it can over complicate a program.

### Numpy

Before we can define arrays in Python we can use the `numpy` library. A library is a collection of commands and functions which we can use by importing the library into your program. The `numpy` library has been designed for scientific computing and contains many commands and functions that are commonly used in mathematics (https://numpy.org/doc/1.18/reference/)

To import `numpy` include the following command in your program.

In [3]:
import numpy as np

The use of this command means we can call the commands from `numpy` using the precursor `np.`

### Defining arrays

To define a one-dimensional array in Python we can use the `np.array()` command.

In [4]:
A = np.array([1, 2, 3])

To display the array `A` we can use the `print()` command.

In [6]:
print(A)

[1 2 3]


Note that the elements in the row vector are contained within square bracket and elements are separated using commas. To define a two-dimensional array (i.e., a matrix) we input multiple row vectors separated by commas.

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


##### Exercise 1

Define arrays in python corresponding to the following vectors and matrices and display them using the `print()` command.

(a) $\mathbf{a} = (1, 3, 5, 7)$

(b) $B = \begin{pmatrix} 1 & -2 \\ 0 & 5 \end{pmatrix}$;

(c) $\mathbf{c}  = \begin{pmatrix} 2 \\ -4 \\ 5 \end{pmatrix}$;

(d) $D = \begin{pmatrix} 1 & 0 & 7 \\ 4 & 7 & 5 \end{pmatrix}$.

### Indexing arrays

In Python, the elements of an array are indexed by their position starting at 0 for the first element (note this is different from MATLAB that uses 1 for the first element). The index is written in square brackets following the array name, for example to index the $i$th element of the array `A`

`A[i]`

For two-dimensional arrays, the indices of an element are separated by a commas, for exmaple to index the element in row $i$ and column $j$ of the array `A`

`A[i,j]`

##### Exercise 2
Using the arrays you defined in exercise 1 and the `print()` command to output the values of (remember that arrays are indexed starting from zero):

(a) $a_1$;

(b) $[B]_{21}$.

### Indexing whole rows or columns

Whole rows or columns of an array can be indexed using a colon `:` in place of the row or column index. For example to index the $i$th row and $j$th column of `A`

`A[i,:]`

`A[:,j]`

##### Exercise 3

Using the arrays you defined in exercise 1 and the `print()` command output:

(a) the second row of $B$;

(b) the third column of $D$.

Note that Python returned a $1\times 2$ array of values for the third column of $D$ instead of a $2\times 1$ array. Python always prints one-dimensional arrays as a row vector unless otherwise stated.

### Generating special arrays

The `numpy` library has some commands that can be used to generate special arrays. To generate an array containing all zeros or all ones we can use the following commands:

`np.zeros()`

`np.ones()`

where the number of elements in the row and columns is given by a tuple within the brackets, e.g., `np.zeros(3)` or `np.zeros((3, 2))`.

In [13]:
A = np.zeros(3)
print(A)

[0. 0. 0.]


In [14]:
A = np.ones((3, 2))
print(A)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


To generate an identity matrix we can use the command `np.eye()` and to generate an array of random numbers in the range $[0,1]$ we can use the `np.random.rand()` command.

##### Exercise 4
Use `numpy` commands to generate the following arrays:
    
(a) A $1\times 5$ array of zeros;

(b) a $3\times 2$ array of ones;

(c) a $2\times 2$ array containing random numbers between 0 and 1;

(d) a $3\times 3$ identity matrix.

### Sequences of numbers

A one-dimensional array containing a sequence of numbers can be generated using the `np.arange()` command.

`np.arange(end)`

This will generate an array containing integer numbers from 0 to `end-1`. For other sequences we can use

`np.arange(start, end, increment)`

This will generate an array of numbers starting at `start` and finishing at `end-1` where the difference between each number is `increment`. When `increment` isn't specified Python will assume an increment of 1.

In [15]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(np.arange(2, 6))

[2 3 4 5]


In [21]:
print(np.arange(1, 9, 2))

[1 3 5 7]


##### Exercise 5
Use the `np.arange()` and `print()` commands to display:

(a) an array containing a list of whole numbers from 0 to 5;

(b) an array containing a list of numbers from 1 to 10 in increments of 3;

(c) an array containing a list of even numbers from 8 to 0.

## Matrix and array operations

### Addition or subraction of arrays

The addition or subraction of two arrays `A` and `B` is achieved using the standard `+` and `-` symbols. 

`A + B`

`A - B`

If `A` and `B` are of different sizes then Python will return an error.



In [27]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A + B)

[5 7 9]


### Scalar multiplication

Scalar multiplication of an array `A` by a scalar quantity `k` is achieved using the `*` symbol (note that this is different from MATLAB where `*` is used to denote matrix multiplication). 

`k*A`

In [32]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(2*A)

[[ 2  4  6]
 [ 8 10 12]]


##### Exercise 6
Given the matrices $A = \begin{pmatrix} 2 & -5 \\ 7 & 3 \end{pmatrix}$ and $B = \begin{pmatrix} 0 & 2 \\ -1 & 5 \end{pmatrix}$ calculate:

(a) $4 + A$;

(b) $3A$;

(c) $A \div 3$.

(d) $B - A$

### Matrix multiplication

Matrix multiplication of two arrays `A` and `B` can be achieved using the `numpy` command

`np.matmul(A, B)`

If the number of columns in `A` is not the same as the number of rows in `B` then this will return an error.

##### Exercise 7
Given the matrixes $A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix}$ calculate:

(a) $AB$;

(b) $BA$.

### Element-wise operations

Element-wise operations are operations that are applied to each element of an array separately. Element-wise operations are the default in Python (in MATLAB matrix operations are considered default). 

For example, to calculate the elements of an array `A` raised to the power of 4.

In [59]:
A = np.array([[1, 2], [3, 4]])
print(A**4)

[[  1  16]
 [ 81 256]]


Whereas to calculate the whole array `A` raised to the power of 4.

In [60]:
print(np.linalg.matrix_power(A, 4))

[[199 290]
 [435 634]]


##### Exercise 8

Given the matrixes $A = \begin{pmatrix} 0 & -2 \\ 3 & 7 \end{pmatrix}$ and $B = \begin{pmatrix} 1 & 3 \\ -7 & 4 \end{pmatrix}$ calculate:

(a) the element-wise multiplication of $A$ and $B$;

(b) each element in $A$ divided by the corresponding element in $B$;


(c) each element in $B$ raised to the power of 3.

### Matrix transpose

To determine the transpose of a matrix we append the command `.T` to the matrix name, i.e.,

`A.T`

In [64]:
A = np.array([[1, 2], [3, 4]])
print(A.T)

[[1 3]
 [2 4]]


##### Exercise 9
Determine the transpose of the matrix $A=\begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix}$.

### Determinant of a matrix

To calculate the determinant of a square matrix `A` we use the `numpy` command

`np.linalg.det(A)`

In [65]:
A = np.matrix([[1, 2], [3, 4]])
detA = np.linalg.det(A)
print(detA)

-2.0000000000000004


### Matrix inverse

To calcualte the inverse of a non-singular square matrix `A` we can use the following `numpy` command

`np.lingalg.inv(A)`

In [52]:
A = np.matrix([[1, 2], [3, 4]])
invA = np.linalg.inv(A)
print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]


### Adjoint of a matrix

To calculate the adjoint of a square matrix `A` we can use the following relationship

$$\operatorname{adj}(A) = \det(A)A^{-1}.$$

In [54]:
A = np.matrix([[1, 2], [3, 4]])
detA = np.linalg.det(A)
invA = np.linalg.inv(A)
print(detA*invA)

[[ 4. -2.]
 [-3.  1.]]


##### Exercise 11
Given the matrix $A=\begin{pmatrix} 1 & 0 & 2 \\ -1 & 3 & 4 \\ 5 & 0 & 2  \end{pmatrix}$.

Use `numpy` commands to calculate:

(a) $\det(A)$;

(b) $A^{-1}$;

(c) $\operatorname{adj}(A)$