# Arrays

In mathematics, **vectors** can be expressed as either a row or column of elements and **matrices** are a rectangular array of elements. An individual element in the vector $\mathbf{a}$ is identified by an **index** denoted using a subscript, e.g., $a_i$. The index is the position of the element in the vector starting at 1 for the first element. An individual element in a matrix is identified by two indices denoted in a subscript, e.g., $[A]_{ij}$, the first number corresponding to the row number and the second number corresponding to the column number.

$$
  \mathbf{a}  = \begin{pmatrix} a_1, & a_2, & \cdots & a_n \end{pmatrix}, \qquad
  \mathbf{b}  = \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{pmatrix}, \qquad
  A           = \begin{pmatrix}
            a_{11} & a_{12} & \cdots & a_{1n} \\
            a_{21} & a_{22} & \cdots & a_{2n} \\
            \vdots & \vdots & \ddots & \vdots \\
            a_{m1} & a_{m2} & \cdots & a_{mn}
          \end{pmatrix}.
$$

In computer programming, a vector or matrix is represented using an **array**. Arrays can be one-dimensional where they contain a single row or column of elements, similar to a vector, or two-dimensional array similar to a matrix. It is possible to have higher dimensional arrays but this is not recommended as it can over complicate a program.

## Contents

1. [Defining arrays](#Defining-arrays)
1. [Indexing arrays](#Indexing-arrays)
1. [Generating special arrays](#Generating-special-arrays)
1. [Sequences of numbers](#Sequences-of-numbers)
1. [Concatenating arrays](#Concatenating-arrays)
1. [Matrix and array operations](#Matrix-and-array-operations)

---
## Defining arrays

### NumPy

To work with matrices and arrays in Python we need to import the **[NumPy](https://numpy.org/doc/stable/index.html)** library. NumPy is a library containing lots of functions which are very useful for scientific computing. To import NumPy execute the code cell below so that all other code cells can use NumPy commands.

In [1]:
import numpy as np

The use of this command means we can call the commands from NumPy using the precursor `np.`

To define a one-dimensional array in Python we can use the `np.array` command ([numpy.array help page](https://numpy.org/doc/stable/reference/arrays.ndarray.html)).

```Python
A = np.array([a1, a2, ... , an ])
```

It is standard practice in programming to use an uppercase character for the first character in the array name. This helps to differentiate between arrays and variables.

#### Example 1
The commands below defines and prints the array corresponding to the vector $\mathbf{a} = (1, 2, 3)$. Enter them into the code cell below and execute it (don't forget to execute the code cell above to use NumPy commands).

```Python
A = np.array([1, 2, 3])
print(A)
```

In [2]:
A = np.array([1, 2, 3])
print(A)

[1 2 3]


Note that the elements in the row vector are contained within square bracket and elements are separated using commas. To define a two-dimensional array (i.e., a matrix) we input multiple row vectors separated by commas.

```Python
A = np.array([[a11, a12, ..., a1n],
              [a21, a22, ..., a2n],
                :    :         :
              [am1, am2, ..., amn]])
```

#### Example 2
The commands below defines the array corresponding to the matrices

$$ A = \begin{pmatrix} 1 & -2 \\ 0 & 5 \end{pmatrix}, \qquad 
B = \begin{pmatrix} 2 \\ -4 \\ 5 \end{pmatrix}, \qquad 
C = \begin{pmatrix} 1 & 0 & 7 \\ 4 & 7 & 5 \end{pmatrix}.$$

and prints them. Enter them into the code cells below and execute each one. 

```Python
import numpy as np

A = np.array([[1, -2],
             [0, 5]])
print(A)
```

In [3]:
import numpy as np

A = np.array([[1, -2],
             [0, 5]])
print(A)

[[ 1 -2]
 [ 0  5]]


```Python
B = np.array([[2], [-4], [5]])
print(B)
```

In [4]:
B = np.array([[2], [-4], [5]])
print(B)

[[ 2]
 [-4]
 [ 5]]


```Python
C = np.array([[1, 0, 7],
             [4, 7, 5]])
print(C)
```

In [5]:
C = np.array([[1, 0, 7],
              [4, 7, 5]])
print(C)

[[1 0 7]
 [4 7 5]]


---
## Exercise 1
1. Define and print arrays corresponding to the following vectors and matrices:
<br>
<br>
(a) $A = \begin{pmatrix}6, & 2, & 4, & -1 \end{pmatrix}$;

In [6]:
A = np.array([6, 2, 4, -1])
print(A)

[ 6  2  4 -1]


&emsp; &emsp; &nbsp; (b) $B = \begin{pmatrix} 3 & 5 & -2 \\ -2 & 4 & 3 \\ 7 & 2 & -1  \end{pmatrix}$;

In [7]:
B = np.array([[3, 5, -2],
              [-2, 4, 3],
              [7, 2, -1]])
print(B)

[[ 3  5 -2]
 [-2  4  3]
 [ 7  2 -1]]


&emsp; &emsp; &nbsp; (c) $C = \begin{pmatrix} 2 & 0 & -1 & 4 \\ 7 & -3 & 9 & -5\end{pmatrix}$;


In [8]:
C = np.array([[2, 0, -1, 4],
              [7, -3, 9, -5]])
print(C)

[[ 2  0 -1  4]
 [ 7 -3  9 -5]]


&emsp; &emsp; &nbsp; (d) $D = \begin{pmatrix} -4 & 4 & 2 \\ 7 & 5 & -3 \\ 5 & 1 & 6 \end{pmatrix}$.

In [9]:
D = np.array([[-4, 4, 2],
              [7, 5, -3,],
              [5, 1, 6]])
print(D)

[[-4  4  2]
 [ 7  5 -3]
 [ 5  1  6]]


---
## Indexing arrays

In Python, the elements of an array are indexed by their position **starting at 0 for the first element**. The index is written in square brackets following the array name.

```Python
A[i]
```

For two-dimensional arrays, the indices of an element are separated by a comma.

```Python
A[i,j]
```

To index elements at the end of a row or column we can use the index `-1` 

```Python
A[-1]
```

The penultimate element is indexed using `-2` and so on.

#### Example 3
The commands below defines the array corresponding to the matrix

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix},$$

and prints individual elements from it using array indexing. Enter them into the code cells below and execute each one.

```Python
import numpy as np

A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(A)
```

In [10]:
import numpy as np

A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


```Python
print(A[0,0]) # output the element in row 1 column 1 of A
```

In [11]:
print(A[0,0]) # output the element in row 1 column 1 of A

1


```Python
print(A[2,1]) # prints the element in row 3 column 2 of A
```

In [12]:
print(A[2,1]) # prints the element in row 3 column 2 of A

8


```Python
print(A[-2,-1]) # print the element in the second to last row and last column of A
```

In [13]:
print(A[-2,-1]) # prints the element in the second to last row and last column of A

6


### Determining the size of an array
The number of elements in a one-dimensional array can be determined using
```
len(A)
```

The number of rows and columns in an two-dimensional array can be determined using the `.shape` property of the array ([numpy.shape help page](https://numpy.org/doc/stable/reference/generated/numpy.shape.html?highlight=shape#numpy.shape)).

```
A.shape
```

This returns the tuple `(rows, columns)` for the array `A`. 

#### Example 4
The following commands defines arrays correpsonding to the matrices

$$A = \begin{pmatrix} 1 & 2 & 3 & 4 \end{pmatrix}, \qquad B = \begin{pmatrix} 1 & 3 & 5 \\ 7 & 9 & 11 \\ 13 & 15 & 17 \\ 19 & 21 & 23 \end{pmatrix}$$

and prints their sizes. Enter them into the code cell below and execute it.

```Python
import numpy as np

A = np.array([1, 2, 3, 4])
B = np.array([[1, 3, 5],
             [7, 9, 11],
             [13, 15, 17],
             [19, 21, 23]])

length_of_A = len(A)
rows_in_B, columns_in_B = B.shape

print("The array A has {} elements.".format(length_of_A))
print("The array B has {} rows and {} columns.".format(rows_in_B, columns_in_B))
```

In [14]:
import numpy as np

A = np.array([1, 2, 3, 4])
B = np.array([[1, 3, 5],
             [7, 9, 11],
             [13, 15, 17],
             [19, 21, 23]])

length_of_A = len(A)
rows_in_B, columns_in_B = B.shape

print("The array A has {} elements.".format(length_of_A))
print("The array B has {} rows and {} columns.".format(rows_in_B, columns_in_B))

The array A has 4 elements.
The array B has 4 rows and 3 columns.


### Array slicing
**Array slicing** allows us to return multiple elements from a NumPy array

```Python
A[start : stop : step]
```

If any these are unspecified Python uses the default values `start=0`, `stop=size of dimension`, `step=1`.


#### Example 5
The following commands defines the array corresponding to the matrix 

$$A = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} $$ 

and uses array slicing to access elements from it. Enter them into the code cells below and execute each one.

```Python
import numpy as np

A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

print(A[0,:]) # print the first row of A
```

In [15]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A[0,:]) # print row 1 of A

[1 2 3]


```Python
print(A[:,1]) # print column 2 of A
```

In [16]:
print(A[:,1]) # print the second column of A

[2 5 8]


Note that Python returned a $1\times 3$ array instead of a $3\times 1$ array. Python always prints one-dimensional arrays as a row vector.

```Python
print(A[1,1:]) # print the elements from column 2 onwards in row 2 of A
```

In [17]:
print(A[1,1:]) # print the elements from column 2 onwards in row 2 of A

[5 6]


```Python
print(A[-1,::-1]) # print the last row of A in reverse column order
```

In [18]:
print(A[-1,::-1]) # print the last row of A in reverse order

[9 8 7]


---
## Exercise 2

2. Define an array corresponding to the matrix $$A = \begin{pmatrix} 6 & -2 & 4 &  0 \\ -4 & 6 & -1 & 2 \\ 4 & -3 & -5 & 6 \end{pmatrix}.$$

In [19]:
A = np.array([[6, -2, 4, 0],
              [-4, 6, -1, 2],
              [4, -3, -5, 6]])
print(A)

[[ 6 -2  4  0]
 [-4  6 -1  2]
 [ 4 -3 -5  6]]



3. Use the array defined in question 2 and array indexing to print:

&emsp; &emsp; &nbsp;  (a) $[A]_{12}$;

In [20]:
print(A[0,1])

-2


&emsp; &emsp; &nbsp; (b) $[A]_{32}$;

In [21]:
print(A[2,1])

-3


&emsp; &emsp; &nbsp; (c) the first row of $A$;

In [22]:
print(A[0,:])

[ 6 -2  4  0]


&emsp; &emsp; &nbsp;  (d) The middle two elements of the second row of $A$;

In [23]:
print(A[1,1:3])

[ 6 -1]


&emsp; &emsp; &nbsp;  (e) The even columns of $A$;

In [24]:
print(A[:,1:4:2])

[[-2  0]
 [ 6  2]
 [-3  6]]


&emsp; &emsp; &nbsp;  (f) The matrix $A$ flipped upside-down (i.e., the rows of $A$ in reverse order).

In [25]:
print(A[::-1,:])

[[ 4 -3 -5  6]
 [-4  6 -1  2]
 [ 6 -2  4  0]]


---
## Generating special arrays
The NumPy library has some commands that can be used to generate special arrays. To generate an array containing all zeros, all ones or the identity matrix we can use the following commands

```
np.zeros((m, n))
np.ones((m, n))
np.eye(n)
```

#### Example 6
The commands below generates special arrays. Enter them into the codel cells below and execute each one.

```Python
import numpy as np

print(np.zeros(3))
```

In [26]:
A = np.zeros(3)
print(A)

[0. 0. 0.]


```Python
print(np.ones((3, 2)))
```

In [27]:
B = np.ones((3, 2))
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


```Python
print(np.eye(4))
```

In [28]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Sequences of numbers

A one-dimensional array containing a sequence of numbers can be generated using the `np.arange` command ([numpy.arange help page](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=numpy%20arange#numpy.arange)).

```Python
np.arange(end)
```

This will generate an array containing integer numbers from 0 to `end-1`. For other sequences we can use

```Python
np.arange(start, end, step)
```

This will generate an array of numbers starting at `start` and finishing at `end-1` where the difference between each number is `step`. When `step` isn't specified Python will assume a step of 1.

#### Example 7
The commands below uses the `np.arange` command to define arrays which contain sequences of numbers. Enter them into the code cells below and execute each one.

```Python
import numpy as np

print(np.arange(10))
```

In [59]:
import numpy as np

print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


```Python
print(np.arange(2, 6))
```

In [30]:
print(np.arange(2, 6))

[2 3 4 5]


```Python
print(np.arange(1, 9, 2))
```

In [31]:
print(np.arange(1, 9, 2))

[1 3 5 7]


---
## Exercise 3

4. Define a $10 \times 10$ array where each element is 1.

In [32]:
import numpy as np

ones = np.ones((10, 10))
print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Define an $8\times 8$ indentity matrix.

In [33]:
import numpy as np

I = np.eye(8)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


6. Use the `np.arange()` command to define an array containing the first ten multiples of 3.

In [34]:
import numpy as np

print(np.arange(3, 33, 3))

[ 3  6  9 12 15 18 21 24 27 30]


---
## Contatenating arrays
NumPy arrays can be **concantenated** (merged) using the `np.concatenate` command ([numpy.concatenate help page](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html?highlight=concatenate#numpy.concatenate))

```
np.concatenate((first matrix, second matrix), axis=0)
```

This will form a new matrix where the `second matrix` is placed below the `first matrix`. To form a matrix where the `second matrix` is placed to the right of the `first matrix` we can use

```
np.concatenate((first matrix, second matrix), axis=1)
```

#### Example 8
The commands below define array corresponding to the matrices

$$A = \begin{pmatrix} 1 & 2 \\ 3 & 3 \end{pmatrix}, \qquad B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix},$$

and concatenates them (the `end="\n\n"` command is used to space out the printed arrays). Enter them into the code cell below and execute it.

```Python
import numpy as np

A = np.array([[1, 2],
             [3, 4]])
B = np.array([[5, 6],
             [7, 8]])

print(A, end="\n\n")
print(B, end="\n\n")
print(np.concatenate((A, B), axis=0), end="\n\n")
print(np.concatenate((A, B), axis=1))
```

In [60]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A, end="\n\n")
print(B, end="\n\n")
print(np.concatenate((A, B), axis=0), end="\n\n") # merge A and B with A on top of B
print(np.concatenate((A, B), axis=1))             # merge A and B side-by-side

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


---
## Matrix and array operations

The Python commands for the common operations on matrices and arrays are summarised in the table below.

| Operation                      | Name | Python code |
|--------------|-------------------------|-------------------------|
| $A + B$      | matrix addition         | `A + B`                 |
| $A - B$      | matrix subtraction      | `A - B`                 |
| $kA$         | scalar multiplication   | `k * A`                 |
| $[A]_{ij}[B]_{ij}$ | element-wise multiplication | `A * B`       |
| $AB$         | matrix multiplication   | `np.matmul(A, B)`       |
| $[A]_{ij}^k$.  | element-wise power      | `A  k`                |
| $A^k$        | matrix power            | `np.linalg.matrix_power(A, k)` |
| $A^T$        | matrix transpose        | `A.T`                   |
| $\det(A)$    | determinant of a matrix | `np.linalg.det(A)`      |
| $A^{-1}$     | inverse of a matrix     | `np.linalg.inv(A)`      |
| $\sin(A)$    | $\sin$ of a matrix* | `np.sin(A)`             |

\* Other mathematical functions are treated similarly.

#### Example 9
The commands below defines arrays corresponding to the matrices

$$A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}, \qquad B = \begin{pmatrix} 5 & 6 \\ 7 & 8 \end{pmatrix},$$ 

and performs operations on them. Enter them into the code cells below and execute each one.

```Python
import numpy as np

A = np.array([[1, 2],
             [3, 4]])
B = np.array([[5, 6],
             [7, 8]])

print(A, end="\n\n")
print(B)
```

In [36]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A, end="\n\n")
print(B)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


```Python
print(A + B) # matrix addition
```

In [37]:
print(A + B) # matrix addition

[[ 6  8]
 [10 12]]


```Python
print(3*A) # scalar multiplication
```

In [38]:
print(3*A) # scalar multiplication

[[ 3  6]
 [ 9 12]]


```Python
print(A*B) # element-wise multiplication
```

In [39]:
print(A*B) # element-wise multiplication

[[ 5 12]
 [21 32]]


```Python
print(np.matmul(A, B)) # matrix multiplication
```

In [40]:
print(np.matmul(A, B)) # matrix multiplication

[[19 22]
 [43 50]]


```Python
print(A3) # element-wise power
```

In [41]:
print(A**3) # element wise matrix power

[[ 1  8]
 [27 64]]


```Python
print(np.linalg.matrix_power(A, 3)) # matrix power
```

In [42]:
print(np.linalg.matrix_power(A, 3)) # matrix power

[[ 37  54]
 [ 81 118]]


```Python
print(A.T) # matrix transpose
```

In [43]:
print(A.T) # matrix transpose

[[1 3]
 [2 4]]


```Python
print(np.linalg.det(A)) # matrix determinant
```

In [44]:
print(np.linalg.det(A)) # matrix determinant

-2.0000000000000004


```Python
print(np.linalg.inv(A)) # inverse matrix
```

In [45]:
print(np.linalg.inv(A)) # inverse matrix

[[-2.   1. ]
 [ 1.5 -0.5]]


```Python
print(np.sin(A)) # sin of the values in matrix A
```

In [46]:
print(np.sin(A)) # sin of the values in matrix A

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


---
## Exercise 4

7. Define arrays corresponding to 

$$A = \begin{pmatrix} 1 & 4 & -2 \\ 0 & 5 & 7 \\ 4 & 1 & -9 \end{pmatrix}, \qquad B = \begin{pmatrix} 5 & 1 & 8 \\ -4 & -2 & 0 \\ 5 & 11 & 3 \end{pmatrix}.$$

In [47]:
A = np.array([[1, 4, -2],
              [0, 5, 7],
              [4, 1, -9]])
B = np.array([[5, 1, 8],
              [-4, -2, 0],
              [5, 11, 3]])

print(A, end='\n\n')
print(B)

[[ 1  4 -2]
 [ 0  5  7]
 [ 4  1 -9]]

[[ 5  1  8]
 [-4 -2  0]
 [ 5 11  3]]


8. Use the arrays you defined in question 7 to calculate:

&emsp; &emsp; &nbsp; (a) $A - 3B$;

In [48]:
print(A - 3*B)

[[-14   1 -26]
 [ 12  11   7]
 [-11 -32 -18]]


&emsp; &emsp; &nbsp; (b) $[A]_{ij}[B]_{ij}$;

In [49]:
print(A*B)

[[  5   4 -16]
 [  0 -10   0]
 [ 20  11 -27]]


&emsp; &emsp; &nbsp; (c) $AB$;

In [50]:
print(np.matmul(A, B))

[[-21 -29   2]
 [ 15  67  21]
 [-29 -97   5]]


&emsp; &emsp; &nbsp; (d) $BA$;

In [51]:
print(np.matmul(B,A))

[[ 37  33 -75]
 [ -4 -26  -6]
 [ 17  78  40]]


&emsp; &emsp; &nbsp; (e) $ABA$;

In [52]:
AB = np.matmul(A, B)
ABA = np.matmul(AB, A)
print(ABA)


[[ -13 -227 -179]
 [  99  416  250]
 [  -9 -596 -666]]


&emsp; &emsp; &nbsp; (f) all elements of $B$ raised to the power of 3;

In [53]:
print(B**3)

[[ 125    1  512]
 [ -64   -8    0]
 [ 125 1331   27]]


&emsp; &emsp; &nbsp; (g) $B^3$;

In [54]:
print(np.linalg.matrix_power(B, 3))

[[ 261  583  680]
 [-220 -364 -192]
 [ 161  503  115]]


 &emsp; &emsp; &nbsp; (h) $A^T$;

In [55]:
print(A.T)

[[ 1  0  4]
 [ 4  5  1]
 [-2  7 -9]]


&emsp; &emsp; &nbsp; (i) $\det(A)$;

In [56]:
print(np.linalg.det(A))

99.99999999999996


&emsp; &emsp; &nbsp; (j) $A^{-1}$;

In [57]:
print(np.linalg.inv(A))

[[-0.52  0.34  0.38]
 [ 0.28 -0.01 -0.07]
 [-0.2   0.15  0.05]]


&emsp; &emsp; &nbsp;  (k) $\cos(B)$.

In [58]:
print(np.cos(B))

[[ 0.28366219  0.54030231 -0.14550003]
 [-0.65364362 -0.41614684  1.        ]
 [ 0.28366219  0.0044257  -0.9899925 ]]


<font size="2"><i>Dr Jon Shiach, Department of Computing and Mathematics, Manchester Metropolitan University</i></font>